version: '3'

services:
  web:
      build: .
      image: drf_movie:tag_drf_movie
      volumes:
          - .:/app/drf_movie
      ports:
          - "8000:8000"
      env_file:
          - ./.env.dev
      command: bash -c "python3 manage.py runserver 0.0.0.0:8000"
      depends_on:
          - db

  db:
      container_name: db_drf
      image: postgres:12.0-alpine
      volumes:
         - postgres_data:/var/lib/postgresql/data/
      environment:
         - POSTGRES_USER=drfuser
         - POSTGRES_PASSWORD=drfmovie
         - POSTGRES_DB=drfmovie

volumes:
  postgres_data:
